### ISSUE TITLE
muster-server caches query

### ISSUE THREAD

**Issue by fabien** [dwstech/muster#37]
**Describe the bug**

This is a follow-up of #27 - turns out the issue is at the server-side, and in the `muster-server` implementation specifically. For whatever reason, requests are being cached and the new graph state is not returned after the first `set()` operation. What's more, the obsolete graph state is returned even after a full reload of the page, or from two independent browsers. 

**To Reproduce**

Muster is setup within Express like so:

```javascript

const musterApp = muster({
  accounts: {
     [match(types.string, 'id')]: fromPromise({
         get: fetchItem,
         set: updateItem // update item and invalidate ref('accounts')
     }),
     [match(types.object, 'filter')]: fromPromise({
         get: findAll,
         set: updateAll // update items and invalidate ref('accounts')
     })
  }
});

musterApp.resolve(query(ref('accounts', {}), entries({ // findAll
    id: true, firstName: true, lastName: true, fullName: true
}))).subscribe(function(result) {
    console.log(JSON.stringify(result, null, 4));
});

app.post('/muster', cors(), bodyParser.json(), musterExpress(musterApp));
```

**Expected behavior**

Client-side, the following code should update the item, invalidate the remote, and automatically re-trigger the subscriber function. However, this function is only called twice - once in initialization, and once after the first successful update.

After that, on a page reload, only the initialization triggers it, and even though it's updated again soon thereafter, it's never triggered again. On reload, the value stays at the first timestamp value set. Even though *the data on the server is updated correctly* each time, no matter what you do, the initial timestamp is returned to the client graph (as mentioned, page reload, different browsers, etc.). This is already the case inside the Express middleware - so it's not the browser caching it (it wouldn't cache POST anyway).

```javascript
const clientApp = muster({
    api: remote('http://localhost:8000/muster', {
        requestTimeout: 2000
    })
});

let q = query(ref('api', 'accounts', 'wilma'), {
    id: true,
    firstName: true,
    lastName: true,
    fullName: true
});

clientApp.resolve(q).subscribe(function(result) {
    console.log(JSON.stringify(result, null, 4));
});

setTimeout(function() {
    const r = ref('api', 'accounts', 'wilma');
    clientApp.resolve(set(r, {
        firstName: new Date().getTime()
    })).then(function(result) {
        return clientApp.resolve(invalidate(ref('api'))).then(function() {
            console.log('Invalidated');
        });
    });
}, 1200);
```
**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Browser [chrome, safari]

**Additional context**

It appears to be related to the ` [match(types.string, 'id')]` construct, together with the `fromPromise` and `set` operation. For example, the same thing using a `set` operation on `[match(types.object, 'filter')]` does work fine (updating all matching items). Same for `[match(types.array, 'ids')]` if it were specified. It's the scalar types that are never released (and remain retained/cached).

**Comment by fabien** [comment]
It should also be noted that calling `resolve` without a subsequent `then` or `subscribe` call goes without any effect. This was extremely misleading while trying to solve the intermittent issue above.

**Comment by dws-dave** [comment]
Thanks for raising this, @fabien - we'll get investigating asap.

**Comment by fabien** [comment]
@dws-dave thanks for chiming in! Merry Christmas! ;-)

**Comment by dws-tomasz** [comment]
Hey @fabien, could you upload some kind of project that reproduces this bug? It would be very helpful to have something to work with 😉

**Comment by fabien** [comment]
Hi @dws-tomasz, in that case I would have to make one. Will look into it later.

**Comment by fabien** [comment]
@dws-tomasz I added a test project here: https://github.com/fabien/muster-demo

It also demonstrates issue #38 - however, for the issue above (by setting `useSockets: false`), I now see `MusterError: Node does not support getChild operation` when reloading the browser. Perhaps I'm overlooking something obvious. I didn't even get to check the invalidation properly this time.

**Comment by dws-dave** [comment]
@fabien I've been digging through your (*excellent*) example repo, and I think i have some updates here. First of all, we've got a fix for #38 coming imminently which will resolve the main problem.

Once that's settled, there's one change you'd need to make to your repo to resolve the `invalid getChild` errors. Your `set` is [currently written](https://github.com/fabien/muster-demo/blob/master/src/index.js#L60) as

```javascript
    clientApp.resolve(set(ref('api', 'accounts', 'one'), {
        name: 'Changed'
    })).then(function() {
        console.log('Updated graph: api.accounts.one');
    });
```

I'd suggest changing it to

```javascript
    // add `toNode` to imports
    clientApp.resolve(set(ref('api', 'accounts', 'one'), toNode({
        id: 'one', name: 'Changed ' + new Date(), active: true 
    }))).then(function() {
        console.log('Updated graph: api.accounts.one');
    }); 
```

The key thing here is that we're including the full item being updated. This is because the `fromPromise` [`set` property](https://github.com/fabien/muster-demo/blob/master/server/index.js#L29) is **only for handling side-effects outside Muster**. As far as Muster is concerned, if you `set` a node to something, that becomes its value, irrespective of any implementation details in the side-effecting code. This is an important concept, and we'll be updating the docs to make it clearer.

I also added a `new Date()` in there to make sure I could see the value change every time the page was reloaded. Because the server process was still running in the background, the value wasn't reset between client app reloads, meaning the `set` could only actually happen once. After that, subsequent `set`s to the same value would trigger no updates anyway, as nothing had changed.

But including the full item every time you want to change just one property is onerous, so you might want to give the [update](https://dwstech.github.io/muster/api/latest/modules/muster.html#update) node a look (sorry about the giant API doc page, we're locked in a war of attrition with typedoc atm). `Update` lets you use an `action` to get the current value of a node and return an updated one, so you could do the `_.extend` there. Check the [RealWorld app](https://dwstech.github.io/muster/api/latest/modules/muster.html#update) for an example (albeit a complicated one).

Once the fix for #38 is released, let's re-test and see if we've got things working.

**Comment by fabien** [comment]
@dws-dave I updated the code (`invalid getChild` error remains for now)

**Comment by dws-dave** [comment]
Oh, that's perplexing. I take it you've also restarted the server? Either way, we'll have a better idea of things once the websocket fix is out.

**Comment by fabien** [comment]
Yes, I'm positive everything has been restarted (and recompiled). Let's see how it goes next week.

**Comment by fabien** [comment]
@dws-dave I've updated to 6.6.1 (thanks!) and while it resolves the socket issue, I'm afraid some weird things remain. I've updated the demo app to reflect this. For some reason, the `clientApp.resolve(set(ref('api', 'accounts', 'one')` operation is not completing (`then` callback never fires) when the the first `set` operation is executed. Also, the `invalid getChild` remains.

**Comment by dws-dave** [comment]
I'll update and check now.

**Comment by dws-dave** [comment]
Ah, found the problem. You also need to add `toNode` to the set, otherwise you're setting an implicit `value` object, meaning that the parent path (`'api', 'accounts', 'one'`) will be set to a JS object (that contains the properties and values you set). Needless to say, that `value` object doesn't have a muster `getChild` operation on it - hence the error message.

In order for Muster to be able to retrieve sub-properties from the path, you need to use `toNode` to convert the JS object into a Muster structure. When then retrieving the sub-path, Muster can resolve all the way to the end and get the individual values.

```diff
+    // don't forget to add toNode to imports
-    clientApp.resolve(set(ref('api', 'accounts', 'one'), {
+    clientApp.resolve(set(ref('api', 'accounts', 'one'), toNode({
        id: 'one', name: 'Changed ' + new Date(), active: true
-    })).then(function() {
+    }))).then(function() {
        console.log('Updated graph: api.accounts.one');
    }).catch(function(err) {
        console.log(err);
    });
```

Not that clear, I grant you. We'll discuss what we can do here to make this situation more obvious.

BTW, you can also use the `set` shorthand, which obviates the need for a `ref`:

```javascript
set('target', 'path', newValue)
```

**Comment by fabien** [comment]
Thanks! Unfortunately it still doesn't work - the last `set` operation is not executed ('Updated graph: api.accounts.one' is never logged to the console), it appears that the former is preventing it from completing. I've updated the code once again - the shorthand `set` is good to know btw!

**Comment by dws-dave** [comment]
Taking a look!

**Comment by dws-dave** [comment]
good news, I've found the error - it's in the websocket implementation, and is 100% my fault. new release asap (which likely means tomorrow due to release process)

**Comment by fabien** [comment]
Hi @dws-dave thanks for the update! No worries about the `set` syntax shorthand btw ;-)
